// default package
// Generated Feb 10, 2008 7:09:48 PM by Hibernate Tools 3.2.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Knight generated by hbm2java
 */
@Entity
@Table(name="knights"
)
public class Knight  implements java.io.Serializable {


     private long id;
     private String name;
     private long numDragonsSlain;
     private Set<Sword> swords = new HashSet<Sword>(0);

    public Knight() {
    }

	
    public Knight(long id, String name, long numDragonsSlain) {
        this.id = id;
        this.name = name;
        this.numDragonsSlain = numDragonsSlain;
    }
    public Knight(long id, String name, long numDragonsSlain, Set<Sword> swords) {
       this.id = id;
       this.name = name;
       this.numDragonsSlain = numDragonsSlain;
       this.swords = swords;
    }
   
     @Id 
    
    @Column(name="knight_id", nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="dragon_count", nullable=false)
    public long getNumDragonsSlain() {
        return this.numDragonsSlain;
    }
    
    public void setNumDragonsSlain(long numDragonsSlain) {
        this.numDragonsSlain = numDragonsSlain;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="knight")
    public Set<Sword> getSwords() {
        return this.swords;
    }
    
    public void setSwords(Set<Sword> swords) {
        this.swords = swords;
    }




}


